uploads = []
generated = []

[[outputs]]
id = "FcoHVInOEe4i3FCb3FLSJ"
uri = "file://MEDSAI/Resources/medsai_loading.gif"
type = "image"
title = "medsai_loading.gif"

[[outputs]]
id = "BXl8dqzZ6KiS9aTA9nRcT"
uri = "file://MEDSAI/Resources/medsai_loading_zoomed.gif"
type = "image"
title = "medsai_loading_zoomed.gif"

[[outputs]]
id = "gaNJRQqkKHFdKoCdfzMbZ"
uri = "file://MEDSAI/Resources/medsai_transparent.gif"
type = "image"
title = "medsai_transparent.gif"

[[outputs]]
id = "JtjHotCdgX2mEGD04RuWB"
uri = "file://MEDSAI/Resources/medsai_transparent2.gif"
type = "image"
title = "medsai_transparent2.gif"

[[outputs]]
id = "B5W_hCNbjQtwu0kEfTsvD"
uri = "file://MEDSAI/Resources/medsai_transparent3.gif"
type = "image"
title = "medsai_transparent3.gif"

[[outputs]]
id = "f9btKqDyDQDZOCWsa95sD"
uri = "file://MEDSAI/Resources/istseh_logo_nobg.mp4"
type = "video"
title = "istseh_logo_nobg.mp4"
